//
// Copyright (c) 2017 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Contributors:
// Steve Fontes

[[tracer]]
== Tracer

The configured Tracer object is accessed by injecting the Tracer class that has been configured for the environment.

[source,java]
----
@Inject Tracer configuredTracer;
----

Access to the configured Tracer gives full access to opentracing.io functions.

Providing the Tracer object enables support for the more complex tracing requirements, such as when a Span is started in one method, and finished in another.

Access to the Tracer also allows tags, logs and baggage to be added to Spans with, for example:
[source,java]
----
configuredTracer.activeSpan().setTag(...);
configuredTracer.activeSpan().log(...);
configuredTracer.activeSpan().setBaggage(...);
----
